### ISSUE TITLE
[BUG]: Hard to swipe left and right on my two tablets?

### ISSUE THREAD

**Issue by lpt2007** [nutteloost/simple-swipe-card#87]
### Current Behavior

Hi,

I put for a test two [bubble-card](https://github.com/Clooos/Bubble-Card) and I have a problems swipe (is working but is hard to swipe) left and right on my 2x tablets. On my PC with mouse swipe working correctly.

### Expected Behavior

To swipe left and right like on my PC:)

### Steps to Reproduce

Just copy / past code and try it on tablet.

### Simple Swipe Card Version

v2.7.0

### Home Assistant Version

16.3

### Device/Platform Running Home Assistant

Virtual Machine (VMware/VirtualBox/etc.)

### Affected Feature

Swipe Navigation

### Dashboard type

Vertical (layout-card)

### YAML Configuration

```yaml
type: custom:simple-swipe-card
show_pagination: false
auto_hide_pagination: 5000
auto_height: false
enable_reset_after: true
reset_target_card: 2
cards:
  - type: custom:bubble-card
    card_type: climate
    entity: climate.room_hallway_climate
    sub_button:
      - entity: climate.room_hallway_climate
        icon: mdi:snowflake
        show_name: false
        tap_action:
          action: call-service
          target:
            entity_id: entity
          data:
            hvac_mode: cool
          service: climate.set_hvac_mode
        show_background: false
      - entity: climate.room_hallway_climate
        icon: mdi:fire
        show_background: false
        tap_action:
          action: perform-action
          perform_action: climate.set_hvac_mode
          target:
            device_id: 675a7fb49546916b5d9bb291dff790ab
          data:
            hvac_mode: heat
      - entity: climate.room_hallway_climate
        icon: mdi:power
        show_background: false
        tap_action:
          action: perform-action
          target:
            device_id: 675a7fb49546916b5d9bb291dff790ab
          perform_action: climate.set_hvac_mode
          data:
            hvac_mode: "off"
    modules:
      - subbutton_colors
      - badgy-condition-helper
      - elits-helper
      - default
      - liquid_glass_light
    show_icon: false
    name: KLIMA
    show_last_changed: true
    subbutton_animations:
      subbutton1:
        animation: bounce
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: cool
      subbutton2:
        animation: bounce
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: heat
      subbutton3:
        animation: bounce
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: "off"
    subbutton_colors:
      subbutton1:
        color: light-blue
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: cool
          - condition: state
            entity_id: climate.room_hallway_climate
            state: "off"
      subbutton2:
        color: red
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: heat
      subbutton3:
        color: red
        condition:
          - condition: state
            entity_id: climate.room_hallway_climate
            state: "off"
    tap_action:
      action: none
    min_temp: 20
    max_temp: 25
    state_color: false
    step: 0.5
    styles: ""
    rows: "1.5"
    card_layout: large
    show_attribute: true
    attribute: current_temperature
    button_action:
      double_tap_action:
        action: none
      hold_action:
        action: navigate
        navigation_path: "#climate"
    badgy-condition-helper:
      sub_buttons_background:
        "0":
          color: blue
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: cool
        "1":
          color: red
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: heat
        "2":
          color: red
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: "off"
      icon_effects:
        sub_button_icon:
          "0":
            effect: rotate
            condition:
              - condition: state
                entity_id: climate.room_hallway_climate
                state: cool
          "1":
            effect: rotate
            condition:
              - condition: state
                entity_id: climate.room_hallway_climate
                state: heat
          "2":
            effect: float
            condition:
              - condition: state
                entity_id: climate.room_hallway_climate
                state: "off"
    elits-helper:
      sub_buttons_background:
        "0":
          color: blue
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: cool
        "1":
          color: blue
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: heat
        "2":
          color: red
          type: solid
          condition:
            - condition: state
              entity_id: climate.room_hallway_climate
              state: "off"
    liquid_glass_light:
      radius: 5
  - type: custom:bubble-card
    card_type: calendar
    event_action:
      tap_action:
        action: more-info
      double_tap_action:
        action: none
      hold_action:
        action: none
    entities:
      - entity: calendar.tasks
        color: cyan
      - entity: calendar.slovenija
        color: yellow
    rows: "1.5"
    sub_button:
      - name: CLOCK
        entity: sensor.time
        show_state: true
        show_icon: false
        state_background: false
        show_background: false
        show_attribute: false
        attribute: friendly_name
        show_last_updated: false
        tap_action:
          action: none
        double_tap_action:
          action: none
      - entity: sensor.date
        show_state: true
        show_icon: false
        show_background: false
        name: DATE
    card_layout: large-2-rows
    modules:
      - liquid_glass_light
    liquid_glass_light:
      radius: 5
```

### Pre-Submission Checklist

- [x] I have searched existing [issues](https://github.com/nutteloost/simple-swipe-card/issues) to ensure this bug hasn't been reported.
- [x] I have provided steps to reproduce the bug.
- [x] I have included the YAML configuration to reproduce the issue.

**Comment by nutteloost** [comment]
Unfortunately I am not able to reproduce this issue on all of my devices, so this will be a hard one to fix... 

1. Does the card follow your finger at all when you try to swipe? (Or does it not move at all until you swipe "correctly"?)

2. When you say "hard" - do you mean:
- You need to swipe faster?
- You need to swipe in a very specific area?
- You need to swipe multiple times before it works?
- The swipe needs to be perfectly horizontal?

3. Does the issue happen with simpler cards too? (Like a basic entities card instead of bubble-card?)
4. What tablet model and browser or app are you using? (iPad/Android, HA companion app/Safari/Chrome/Firefox?)
5. Does it happen on all dashboard types or just the Layout-card dashboard? 

Please provide as much detailed information to narrow down this issue as much as possible.

**Comment by lpt2007** [comment]
Hi, I have FKB with swipe navigation off, but problem still occurs.

**Comment by BalooDK** [comment]
I have the same problem. Also using Fully on an M10
Since 'swipe card' works smoothly, i think the problem is with 'simple swipe card' and not the Fully Kiosk Browser

**Comment by nutteloost** [comment]
In the latest release I have implemented some fixes that will prevent other browsers interrupting swipe events. This will likely fix these issues. Please download [v3.0.1](https://github.com/nutteloost/simple-swipe-card/releases/tag/v3.0.1) and let me know if it is fixed.

**Comment by BalooDK** [comment]
This fixed it for me. thank you

**Comment by StrandmonYellow** [comment]
I am still having this issue in 3.1.0. I have had this issue for a while already (a couple of months i think). I am not running fully kiosk browser, just using a custom card on my phone dashboard. 

@nutteloost 

https://github.com/user-attachments/assets/45eba832-874a-4c59-8197-45212531860e

**Comment by Masterrar1** [comment]
> I am still having this issue in 3.1.0. I have had this issue for a while already (a couple of months i think). I am not running fully kiosk browser, just using a custom card on my phone dashboard.
> 
> [@nutteloost](https://github.com/nutteloost)
> 
>  Screen_Recording_20260617_215701_Home.Assistant.mp4
Same here. The issue is there on my wallpanel with Fully Kiosk Browser and also on the iPhone inside the Home Assistant-App (testing with the same dashboard).

**Comment by nutteloost** [comment]
@StrandmonYellow , please provide more information. Your configuration, what kind of dashboard, which browser and any other useful information that may help fixing the issue.

**Comment by StrandmonYellow** [comment]
I am sorry for the delayed response. This is the Yaml part of my dashboard with the swipe card:

```
  - type: custom:simple-swipe-card
    start_card: 0       # always starts at the first card
    show_pagination: false
    parameters:
      centeredSlides: true
      slidesPerView: auto
      spaceBetween: 24
    cards:
      - type: sensor
        entity: sensor.aru_temperatuur
        hours_to_show: 24
        detail: 1
        graph: line
        name: Temperatuur
        icon: none
        card_mod:
          class: graph
          style: |
            ha-card {
              --accent-color: var(--blue);
            }
            .graph {
            background: var(--blue-tint);
            }
      - type: sensor
        entity: sensor.hue_motion_sensor_1_licht
        hours_to_show: 24
        detail: 1
        graph: line
        name: Lichtintensiteit
        icon: none
        card_mod:
          class: graph
          style: |
            ha-card {
              --accent-color: var(--yellow);
            }
            .graph {
            background: var(--yellow-tint);
            }
      - type: sensor
        entity: sensor.ikea_luchtkwaliteit_sensor_luchtvochtigheid
        hours_to_show: 24
        detail: 1
        graph: line
        name: Luchtvochtigheid
        icon: none
        card_mod:
          class: graph
          style: |
            ha-card {
              --accent-color: var(--blue);
            }
            .graph {
            background: var(--blue-tint);
            }
      - type: sensor
        entity: sensor.ikea_luchtkwaliteit_sensor_pm_2_5
        hours_to_show: 24
        detail: 1
        graph: line
        name: Luchtkwaliteit 
        icon: none
        card_mod:
          class: graph
          style: |
            ha-card {
              --accent-color: var(--red);
            }
            .graph {
            background: var(--red-tint);
            }
``` 

I am using this with the Rounded Theme applied to my dashboard: https://community.home-assistant.io/t/rounded-dashboard-guide/543043

I am using a Samsung Smartphone running android 16 and one UI 8.0. HA android app: 2026.6.5-full (22884)
The browser will be the builtin browser that the HA app is using, but as i said i have this issue for a while now so its since an earlier release. Using my builtin Samsung Browser does not completely fix the issue, but it seems to make it a bit better. 

If you need any more information let me know.

**Comment by StrandmonYellow** [comment]
Hi, 

For me this is still a problem. What more information do you need in order to look into it? @nutteloost
